"use strict";

// Admin: Create app user + send activation email invite.
//
// Endpoint:
//   POST /api/admin/users
// Body:
//   {
//     "email": "user@company.com",          (required)
//     "role": "TRADE_ADMIN",                (required)
//     "employee_id": 123,                   (optional)
//     "username": "yahya",                  (optional; autogenerated if missing)
//     "note": "optional note",              (optional)
//     "full_name": "Yahya ..."              (optional)
//   }
//
// Valid roles: IT_ADMIN, COMPANY_ADMIN, TRADE_PROJECT_MANAGER, TRADE_ADMIN, WORKER

const express = require("express");
const crypto  = require("crypto");
const { hashPin }        = require("../lib/auth_utils");
const { normalizeRole }  = require("../middleware/roles");
const { can }            = require("../middleware/permissions");
const sgMail = require("@sendgrid/mail");
const { pool } = require("../db");

const router = express.Router();

// ── Valid roles (new unified system only) ─────────────────────
const ALLOWED_ROLES = new Set([
  "IT_ADMIN",
  "COMPANY_ADMIN",
  "TRADE_PROJECT_MANAGER",
  "TRADE_ADMIN",
  "WORKER",
]);

// ── Role rank — callers cannot create users with equal/higher role ──
const ROLE_RANK = {
  SUPER_ADMIN:           0,
  IT_ADMIN:              1,
  COMPANY_ADMIN:         2,
  TRADE_PROJECT_MANAGER: 3,
  TRADE_ADMIN:           4,
  WORKER:                5,
};

function mustEnv(name) {
  const v = process.env[name];
  if (!v || !String(v).trim()) return null;
  return String(v).trim();
}

function normalizeEmail(email) {
  return String(email || "").trim().toLowerCase();
}

function isValidEmail(email) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

function sanitizeUsername(s) {
  const raw     = String(s || "").trim().toLowerCase();
  const cleaned = raw.replace(/[^a-z0-9._]/g, "_");
  return cleaned.replace(/_+/g, "_").replace(/^_+|_+$/g, "");
}

async function ensureUniqueUsername(base) {
  let candidate = base;
  if (!candidate || candidate.length < 3) {
    candidate = `user_${crypto.randomBytes(3).toString("hex")}`;
  }
  for (let i = 0; i < 20; i++) {
    const name = i === 0 ? candidate : `${candidate}${i}`;
    const { rows } = await pool.query(
      `SELECT 1 FROM public.app_users WHERE username = $1 LIMIT 1`,
      [name]
    );
    if (!rows.length) return name;
  }
  return `${candidate}_${crypto.randomBytes(3).toString("hex")}`;
}

// POST /api/admin/users
// Requires: settings.user_management permission
router.post("/", can("settings.user_management"), async (req, res) => {
  try {
    const SENDGRID_API_KEY    = mustEnv("SENDGRID_API_KEY");
    const SENDGRID_FROM_EMAIL = mustEnv("SENDGRID_FROM_EMAIL");
    const APP_BASE_URL        = mustEnv("APP_BASE_URL");

    if (!SENDGRID_API_KEY || !SENDGRID_FROM_EMAIL || !APP_BASE_URL) {
      return res.status(500).json({
        ok: false,
        error: "EMAIL_NOT_CONFIGURED",
        message: "Missing SENDGRID_API_KEY / SENDGRID_FROM_EMAIL / APP_BASE_URL in .env",
      });
    }

    const email      = normalizeEmail(req.body?.email);
    const role       = normalizeRole(req.body?.role);  // normalizes legacy aliases too
    const employeeId = req.body?.employee_id ?? null;
    const note       = req.body?.note ?? null;
    const fullName   = req.body?.full_name ?? null;
    const usernameRaw = req.body?.username ?? null;

    // ── Validate inputs ───────────────────────────────────────
    if (!email || !isValidEmail(email)) {
      return res.status(400).json({ ok: false, error: "INVALID_EMAIL" });
    }

    if (!role) {
      return res.status(400).json({ ok: false, error: "ROLE_REQUIRED" });
    }

    if (!ALLOWED_ROLES.has(role)) {
      return res.status(400).json({
        ok: false,
        error: "INVALID_ROLE",
        allowed: Array.from(ALLOWED_ROLES),
        received: role,
      });
    }

    // Caller cannot create a user with equal or higher privilege
    const callerRole = normalizeRole(req.user?.role);
    const callerRank = ROLE_RANK[callerRole] ?? 99;
    const targetRank = ROLE_RANK[role] ?? 99;

    if (callerRank >= targetRank) {
      return res.status(403).json({
        ok: false,
        error: "INSUFFICIENT_PRIVILEGE",
        message: `Cannot create a user with role "${role}" — you need a higher role than the target`,
      });
    }

    const companyId        = req.user?.company_id ?? null;
    const createdByUserId  = req.user?.user_id ?? null;

    // ── Atomic create user + invite ───────────────────────────
    const client = await pool.connect();
    try {
      await client.query("BEGIN");

      // Duplicate check
      const exists = await client.query(
        `SELECT id, username, role, is_active, activated_at
         FROM public.app_users
         WHERE (company_id IS NOT DISTINCT FROM $1)
           AND lower(email) = lower($2)
         LIMIT 1`,
        [companyId, email]
      );
      if (exists.rows.length) {
        await client.query("ROLLBACK");
        return res.status(409).json({
          ok: false,
          error: "USER_EMAIL_EXISTS",
          user: exists.rows[0],
        });
      }

      // Generate username
      const base     = sanitizeUsername(usernameRaw || email.split("@")[0]);
      const username = await ensureUniqueUsername(base);

      // Random PIN — user sets real PIN during activation
      const randomPin = crypto.randomBytes(6).toString("base64url");
      const pinHash   = await hashPin(randomPin);

      const insUser = await client.query(
        `INSERT INTO public.app_users
          (username, pin_hash, employee_id, role, is_active, company_id, email,
           profile_status, activation_sent_at, activated_at, last_invite_id)
         VALUES ($1, $2, $3, $4, true, $5, $6, 'NEW', NULL, NULL, NULL)
         RETURNING id, username, email, role, employee_id, company_id, is_active, profile_status`,
        [username, pinHash, employeeId, role, companyId, email]
      );
      const newUser = insUser.rows[0];

      // Revoke existing active invites for this email
      await client.query(
        `UPDATE public.user_invites
         SET status='REVOKED', revoked_at=NOW()
         WHERE (company_id IS NOT DISTINCT FROM $1)
           AND lower(email)=lower($2)
           AND status='ACTIVE'`,
        [companyId, email]
      );

      // Generate activation token
      const rawToken  = crypto.randomBytes(32).toString("base64url");
      const tokenHash = crypto.createHash("sha256").update(rawToken).digest("hex");

      const expiresHours = Number(process.env.USER_INVITE_EXPIRES_HOURS || 48);
      const expiresAt    = new Date(Date.now() + Math.max(1, expiresHours) * 60 * 60 * 1000);

      const noteParts = [];
      if (note)     noteParts.push(String(note));
      if (fullName) noteParts.push(`full_name=${String(fullName)}`);
      noteParts.push(`created_user_id=${newUser.id}`);

      const insInvite = await client.query(
        `INSERT INTO public.user_invites
          (company_id, employee_id, email, role, token_hash, status, created_by_user_id, note, expires_at)
         VALUES ($1, $2, $3, $4, $5, 'ACTIVE', $6, $7, $8)
         RETURNING id`,
        [companyId, employeeId, email, role, tokenHash, createdByUserId, noteParts.join(" | "), expiresAt]
      );
      const inviteId = insInvite.rows?.[0]?.id;
      if (!inviteId) throw new Error("Failed to create invite");

      // Send activation email
      sgMail.setApiKey(SENDGRID_API_KEY);
      const activateLink = `${APP_BASE_URL.replace(/\/$/, "")}/activate?token=${rawToken}`;

      const roleLabel = {
        IT_ADMIN:              "IT Administrator",
        COMPANY_ADMIN:         "Company Administrator",
        TRADE_PROJECT_MANAGER: "Trade Project Manager",
        TRADE_ADMIN:           "Trade Administrator",
        WORKER:                "Worker",
      }[role] || role;

      const html = `
        <div style="font-family: Arial, sans-serif; line-height:1.6; max-width:500px">
          <h2 style="color:#0f172a">Activate your MEP Platform account</h2>
          <p>You've been invited as <strong>${roleLabel}</strong>.</p>
          <p>Click the link below to set up your account:</p>
          <p><a href="${activateLink}" style="color:#6366f1">${activateLink}</a></p>
          <p style="color:#94a3b8;font-size:13px">This link expires in ${expiresHours} hours.</p>
        </div>
      `;

      await sgMail.send({
        to:      email,
        from:    SENDGRID_FROM_EMAIL,
        subject: "Activate your MEP Platform account",
        html,
      });

      await client.query(
        `UPDATE public.user_invites SET sent_at=NOW() WHERE id=$1`,
        [inviteId]
      );
      await client.query(
        `UPDATE public.app_users SET activation_sent_at=NOW(), last_invite_id=$2 WHERE id=$1`,
        [newUser.id, inviteId]
      );

      await client.query("COMMIT");

      return res.status(201).json({
        ok:              true,
        user:            newUser,
        invite_id:       inviteId,
        expires_at:      expiresAt.toISOString(),
        activation_link: activateLink,
      });

    } catch (e) {
      await client.query("ROLLBACK");
      throw e;
    } finally {
      client.release();
    }

  } catch (err) {
    console.error("POST /api/admin/users error:", err);
    return res.status(500).json({
      ok: false,
      error: "ADMIN_CREATE_USER_FAILED",
      message: err.message,
    });
  }
});

module.exports = router;
