"use strict";

// Admin: Create app user + send activation email invite.
//
// Endpoint:
//   POST /api/admin/users
// Body:
//   {
//     "email": "user@company.com",   (required)
//     "role": "PURCHASING",         (required)
//     "employee_id": 123,            (optional)
//     "username": "yahya",          (optional; autogenerated if missing)
//     "note": "optional note",      (optional; stored on invite)
//     "full_name": "Yahya ..."      (optional; stored on invite note)
//   }
//
// Notes:
// - We intentionally generate a random PIN hash (unknown to the user) so the account cannot be used
//   until the activation + credential setup flow is completed in a later step.

const express = require("express");
const crypto = require("crypto");
const { hashPin } = require("../lib/auth_utils");
const sgMail = require("@sendgrid/mail");
const { pool } = require("../db");

const router = express.Router();

function mustEnv(name) {
  const v = process.env[name];
  if (!v || !String(v).trim()) return null;
  return String(v).trim();
}

function normalizeEmail(email) {
  return String(email || "").trim().toLowerCase();
}

function isValidEmail(email) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

function normalizeRole(role) {
  return String(role || "").trim().toUpperCase();
}


function sanitizeUsername(s) {
  const raw = String(s || "").trim().toLowerCase();
  // Allow a-z, 0-9, underscore, dot.
  const cleaned = raw.replace(/[^a-z0-9._]/g, "_");
  // Trim repeated underscores
  return cleaned.replace(/_+/g, "_").replace(/^_+|_+$/g, "");
}

async function ensureUniqueUsername(base) {
  let candidate = base;
  if (!candidate || candidate.length < 3) candidate = `user_${crypto.randomBytes(3).toString("hex")}`;

  // Try up to 20 variants.
  for (let i = 0; i < 20; i++) {
    const name = i === 0 ? candidate : `${candidate}${i}`;
    const { rows } = await pool.query(
      `SELECT 1 FROM public.app_users WHERE username = $1 LIMIT 1`,
      [name]
    );
    if (!rows.length) return name;
  }
  // Fallback.
  return `${candidate}_${crypto.randomBytes(3).toString("hex")}`;
}

// POST /api/admin/users
router.post("/", async (req, res) => {
  try {
    const SENDGRID_API_KEY = mustEnv("SENDGRID_API_KEY");
    const SENDGRID_FROM_EMAIL = mustEnv("SENDGRID_FROM_EMAIL");
    const APP_BASE_URL = mustEnv("APP_BASE_URL");

    if (!SENDGRID_API_KEY || !SENDGRID_FROM_EMAIL || !APP_BASE_URL) {
      return res.status(500).json({
        ok: false,
        error: "EMAIL_NOT_CONFIGURED",
        message: "Missing SENDGRID_API_KEY / SENDGRID_FROM_EMAIL / APP_BASE_URL in .env",
      });
    }

    const email = normalizeEmail(req.body?.email);
    const role = normalizeRole(req.body?.role);
    const employeeId = req.body?.employee_id ?? null;
    const note = req.body?.note ?? null;
    const fullName = req.body?.full_name ?? null;
    const usernameRaw = req.body?.username ?? null;

    if (!email || !isValidEmail(email)) {
      return res.status(400).json({ ok: false, error: "INVALID_EMAIL" });
    }
    if (!role) {
      return res.status(400).json({ ok: false, error: "ROLE_REQUIRED" });
    }

    const allowedRoles = new Set(["ADMIN", "PM", "FOREMAN", "WORKER", "PURCHASING"]);
    if (!allowedRoles.has(role)) {
      return res.status(400).json({ ok: false, error: "INVALID_ROLE", allowed: Array.from(allowedRoles) });
    }

    const companyId = req.user?.company_id ?? null;
    const createdByUserId = req.user?.user_id ?? null;

    // Create user + invite atomically.
    const client = await pool.connect();
    try {
      await client.query("BEGIN");

      // Prevent duplicate user by email within same company_id (NULL-safe).
      const exists = await client.query(
        `SELECT id, username, role, is_active, activated_at
         FROM public.app_users
         WHERE (company_id IS NOT DISTINCT FROM $1)
           AND lower(email) = lower($2)
         LIMIT 1`,
        [companyId, email]
      );
      if (exists.rows.length) {
        await client.query("ROLLBACK");
        return res.status(409).json({
          ok: false,
          error: "USER_EMAIL_EXISTS",
          user: exists.rows[0],
        });
      }

      // Username generation.
      const base = sanitizeUsername(usernameRaw || email.split("@")[0]);
      const username = await (async () => {
        // Use pool for uniqueness checks but still ok; usernames are global.
        const u = await ensureUniqueUsername(base);
        return u;
      })();

      // Random PIN (not revealed). User will set real PIN in a later step.
      const randomPin = crypto.randomBytes(6).toString("base64url");
      const pinHash = await hashPin(randomPin);

      const insUser = await client.query(
        `INSERT INTO public.app_users
          (username, pin_hash, employee_id, role, is_active, company_id, email, profile_status, activation_sent_at, activated_at, last_invite_id)
         VALUES
          ($1, $2, $3, $4, true, $5, $6, 'NEW', NULL, NULL, NULL)
         RETURNING id, username, email, role, employee_id, company_id, is_active, profile_status`,
        [username, pinHash, employeeId, role, companyId, email]
      );
      const newUser = insUser.rows[0];

      // Revoke any existing ACTIVE invite for same (company_id, email).
      await client.query(
        `UPDATE public.user_invites
         SET status='REVOKED', revoked_at=NOW()
         WHERE (company_id IS NOT DISTINCT FROM $1)
           AND lower(email)=lower($2)
           AND status='ACTIVE'`,
        [companyId, email]
      );

      // Generate raw token for email link.
      const rawToken = crypto.randomBytes(32).toString("base64url");
      const tokenHash = crypto.createHash("sha256").update(rawToken).digest("hex");

      const expiresHours = Number(process.env.USER_INVITE_EXPIRES_HOURS || 48);
      const expiresAt = new Date(Date.now() + Math.max(1, expiresHours) * 60 * 60 * 1000);

      const combinedNoteParts = [];
      if (note) combinedNoteParts.push(String(note));
      if (fullName) combinedNoteParts.push(`full_name=${String(fullName)}`);
      combinedNoteParts.push(`created_user_id=${newUser.id}`);
      const combinedNote = combinedNoteParts.join(" | ");

      const insInvite = await client.query(
        `INSERT INTO public.user_invites
          (company_id, employee_id, email, role, token_hash, status, created_by_user_id, note, expires_at)
         VALUES ($1, $2, $3, $4, $5, 'ACTIVE', $6, $7, $8)
         RETURNING id`,
        [companyId, employeeId, email, role, tokenHash, createdByUserId, combinedNote, expiresAt]
      );
      const inviteId = insInvite.rows?.[0]?.id;
      if (!inviteId) throw new Error("Failed to create invite");

      // Send email (if send fails, rollback everything).
      sgMail.setApiKey(SENDGRID_API_KEY);
      const activateLink = `${APP_BASE_URL.replace(/\/$/, "")}/activate?token=${rawToken}`;

      const html = `
        <div style="font-family: Arial, sans-serif; line-height:1.4">
          <h2>Activate your account</h2>
          <p>Please activate your account by clicking the link below:</p>
          <p><a href="${activateLink}">${activateLink}</a></p>
          <p>This link expires at: <b>${expiresAt.toISOString()}</b></p>
          <p>If you did not request this, you can ignore this email.</p>
        </div>
      `;

      await sgMail.send({
        to: email,
        from: SENDGRID_FROM_EMAIL,
        subject: "Activate your account",
        html,
      });

      await client.query(`UPDATE public.user_invites SET sent_at=NOW() WHERE id=$1`, [inviteId]);
      await client.query(`UPDATE public.app_users SET activation_sent_at=NOW(), last_invite_id=$2 WHERE id=$1`, [newUser.id, inviteId]);

      await client.query("COMMIT");

      return res.status(201).json({
        ok: true,
        user: newUser,
        invite_id: inviteId,
        expires_at: expiresAt.toISOString(),
        activation_link: activateLink,
      });
    } catch (e) {
      await client.query("ROLLBACK");
      throw e;
    } finally {
      client.release();
    }
  } catch (err) {
    console.error("POST /api/admin/users error:", err);
    return res.status(500).json({ ok: false, error: "ADMIN_CREATE_USER_FAILED", message: err.message });
  }
});

module.exports = router;
